Repository HenryBcit/classDAISetB, pull requests merged in 2019-09, with the labels that each got.

#7 first commit
  Micah/index.js
Labels: help wanted

#2 first commit
  Siya/index.js
Labels: question

#6 first commit
  index.js
Labels: bug, question

#8 Initial Commit
  bin/index.html
Labels: good first issue

#1 my first commit
  Henry/index.js
Labels: bug, duplicate
